name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string
      
      file:
        description: 'File to execute'
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - sum

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"

  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
      - run: python ${{ inputs.file }}.py ejecucion
      
